"""Init skill 表单字段定义 — Task 102."""
from __future__ import annotations

INIT_STEP_SCHEMAS = {
    "step_1": {
        "title": "故事核与商业定位",
        "fields": [
            {"name": "title", "label": "书名", "type": "text", "required": True},
            {"name": "genres", "label": "题材", "type": "multi_select", "required": True,
             "hint": "支持复合题材，至少选一个",
             "options": ["修仙", "玄幻", "都市", "科幻", "悬疑", "狗血言情", "古言", "现实题材", "规则怪谈", "知乎短篇", "历史", "游戏", "末世", "校园"]},
            {"name": "target_words", "label": "目标字数（万字）", "type": "number", "default": 200,
             "hint": "如 200 表示 200 万字"},
            {"name": "target_chapters", "label": "目标章节数", "type": "number", "default": 600},
            {"name": "one_line_story", "label": "一句话故事", "type": "text", "required": True,
             "hint": "用一句话概括你的故事核心"},
            {"name": "core_conflict", "label": "核心冲突", "type": "textarea", "required": True},
            {"name": "target_audience", "label": "目标读者", "type": "text"},
        ],
    },
    "step_2": {
        "title": "角色骨架与关系冲突",
        "fields": [
            {"name": "protagonist_name", "label": "主角姓名", "type": "text", "required": True},
            {"name": "protagonist_desire", "label": "主角欲望", "type": "textarea", "required": True,
             "hint": "主角最想要什么？"},
            {"name": "protagonist_flaw", "label": "主角缺陷", "type": "textarea", "required": True,
             "hint": "主角最大的性格缺陷"},
            {"name": "protagonist_structure", "label": "主角成长结构", "type": "select",
             "options": ["正向成长弧", "堕落弧", "平坦弧", "复杂弧"]},
            {"name": "romance_config", "label": "感情线配置", "type": "select",
             "options": ["无感情线", "单女主", "后宫", "暧昧不明"]},
            {"name": "villain_tiers", "label": "反派分层", "type": "textarea",
             "hint": "小反派→中反派→大反派，每层简述"},
        ],
    },
    "step_3": {
        "title": "金手指与兑现机制",
        "fields": [
            {"name": "golden_finger_type", "label": "金手指类型", "type": "select", "required": True,
             "hint": "网文术语：主角独有的超能力或优势，如系统、重生记忆等",
             "options": ["系统流", "重生", "传承", "异能", "无金手指", "其他"]},
            {"name": "golden_finger_name", "label": "金手指名称", "type": "text", "required": False,
             "hint": "给金手指起个名字，如“天道系统”",
             "hide_when": {"golden_finger_type": "无金手指"}},
            {"name": "golden_finger_style", "label": "风格", "type": "select",
             "options": ["科技感", "古典", "神秘", "搞笑", "暗黑"],
             "hide_when": {"golden_finger_type": "无金手指"}},
            {"name": "golden_finger_visibility", "label": "可见度", "type": "select",
             "options": ["仅主角可见", "部分人可见", "公开"],
             "hide_when": {"golden_finger_type": "无金手指"}},
            {"name": "golden_finger_cost", "label": "不可逆代价", "type": "textarea",
             "hint": "使用金手指的代价是什么？",
             "hide_when": {"golden_finger_type": "无金手指"}},
            {"name": "golden_finger_growth", "label": "成长节奏", "type": "select",
             "options": ["线性成长", "阶梯式", "指数爆发", "先抑后扬"],
             "hide_when": {"golden_finger_type": "无金手指"}},
        ],
    },
    "step_4": {
        "title": "世界观与力量规则",
        "fields": [
            {"name": "world_scale", "label": "世界规模", "type": "select", "required": True,
             "options": ["单城市", "单大陆", "多大陆", "星际", "多位面"]},
            {"name": "power_system", "label": "力量体系", "type": "textarea", "required": True,
             "hint": "描述修炼/力量等级体系"},
            {"name": "faction_layout", "label": "势力格局", "type": "textarea",
             "hint": "主要势力及其关系"},
            {"name": "social_hierarchy", "label": "社会阶层", "type": "textarea",
             "hint": "社会等级结构"},
        ],
    },
}
